### ISSUE TITLE
Interpreting the skeleton Data in the text file

### ISSUE THREAD

**Issue by ChaitanyaGanu** [xiaozhuchacha/Kinect2Toolbox#1]
Hello, I am currently working on a project which needs to use the relative positions of the joints of one's upper body. I am using the Kinect V2 Toolbox to try and get these values. When I run the ColorDepthSkeletonRecorder from pipeline I get a text file with some numbers. Can you explain what these numbers are? 

I assume that the numbers 0-24 refer to each of the joints but corresponding to each joint there are 7 coordinates. Can you please explain the meaning of these values?

Can you also explain what the rest of the values signify?
![kinect_toolbox_issue](https://user-images.githubusercontent.com/28176226/27382818-13a59a8a-56a6-11e7-8732-6b86678d2c53.JPG)

**Comment by xiaozhuchacha** [comment]
A sample code to process the skeleton data was demonstrated using a matlab script. See Pipeline/matlab_viz

First 25 rows are skeleton positions:
- 1st column is index
- 2-4 columns are 3d positions
- 5th column is the state: missed, estimated, and tracked
- 6-7 columns should be the 2d positions on depth map
- 8-9 columns should be the 2d positions on the visualized gui.

Following two lines are hand states

Final sections are quaternions of each joint.

**Comment by ChaitanyaGanu** [comment]
Thank you very much! I got what I was looking for! Great work!

**Comment by beckyng2194** [comment]
@ChaitanyaGanu I'm hoping to get these same results, but having a hard time getting the code to run. I'm hoping you can tell me what version of OpenCV you used and whether you use VS 2015 or 2017? thanks

**Comment by ChaitanyaGanu** [comment]
@beckyng2194 Hi! I used VS 2015 and OpenCV 3.

**Comment by beckyng2194** [comment]
@ChaitanyaGanu thanks so much. Finally got the code running. Also thanks to @xiaozhuchacha for the very helpful toolbox
